# Generated by Django 6.1 on 2026-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_covers', models.PositiveIntegerField(default=1)),
                ('max_covers', models.PositiveIntegerField()),
                ('section', models.CharField(choices=[('main', 'Main Dining'), ('window', 'Window'), ('patio', 'Patio'), ('bar', 'Bar'), ('private', 'Private Room')], default='main', max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tables are soft-deleted — hidden from the floor plan but kept for historical bookings.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('min_covers', models.PositiveIntegerField()),
                ('max_covers', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('tables', models.ManyToManyField(related_name='combinations', to='tables.table')),
            ],
        ),
    ]
