# Generated by Django 6.1 on 2026-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.FloatField(default=80, help_text='Height in pixels on the floor plan canvas'),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.FloatField(default=80, help_text='Width in pixels on the floor plan canvas'),
        ),
    ]
