# Generated by Django 6.1 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_height_table_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Fixed in place (e.g. bar seating) - excluded from drag-and-drop repositioning'),
        ),
    ]
