# Generated by Django 6.1 on 2026-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('last_booking_time', models.TimeField(help_text='Latest time a booking can be made for this service')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30, help_text='Interval between available booking slots, e.g. 15 or 20 minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=True)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Special hours',
                'ordering': ['date'],
            },
        ),
    ]
