# Generated by Django 6.1 on 2026-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_status',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_email_status',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
