# Generated by Django 6.1 on 2026-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_confirmation_email_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manage_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
