# Generated by Django 6.1 on 2026-09-01 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_manage_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='manage_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
