# Generated by Django 6.1 on 2026-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_manage_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
