# Generated by Django 6.1 on 2026-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
