# Generated by Django 6.1 on 2026-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
