# Generated by Django 6.1 on 2026-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_guest_booking_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='notifcation_email_status',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
