# Generated by Django 6.1 on 2026-10-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_waitlist_notifcation_email_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlist',
            old_name='notifcation_email_status',
            new_name='notification_email_status',
        ),
    ]
